### ISSUE TITLE
Listeria monocytogenes database is missing graph file.

### ISSUE THREAD

**Issue by DOH-JDJ0303** [bacpop/PopPUNK#300] opened 2024-02-13 18:52 UTC
The _Listeria monocytogenes_ database on bacpop.org is missing the required graph file. I have only tested this for the reference database, as the full sample set was taking too long to download. The list of files in the ref database is shown below:

```
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs_clusters.csv
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs.dists.npy
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs.refs
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs_unword_clusters.csv
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs_fit.pkl
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs.dists.pkl
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs.h5
  listeria_monocytogenes_v2_refs/listeria_monocytogenes_v2_refs_fit.npz
```

**Comment by DOH-JDJ0303** [comment] 2024-02-13 20:59
Adding to this the _Neisseria meningitidis_ reference database also appears to be missing the *_fit.npz file. Below are a list of the files that come with the database.

```
Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs_unword_clusters.csv
  Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs_clusters.csv
  Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs.dists.pkl
  Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs.h5
  Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs.refs
  Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs.dists.npy
  Neisseria_meningitidis_v1_refs/Neisseria_meningitidis_v1_refs.refs_graph.gt
```

**Comment by johnlees** [comment] 2024-02-14 15:58
Apologies for this, we will look into and update soon

**Comment by DOH-JDJ0303** [comment] 2024-02-16 04:15
Thank you, @johnlees. To add to this, it also appears that the _Streptococcus pneumoniae_ and _Streptococcus pyogenes_ reference database links are broken.

**Comment by johnlees** [comment] 2024-02-16 16:46
> Thank you, @johnlees. To add to this, it also appears that the _Streptococcus pneumoniae_ and _Streptococcus pyogenes_ reference database links are broken.

Thanks very much for pointing this out too. This was just a typo in the website, which I've just fixed

**Comment by johnlees** [comment] 2024-02-26 17:00
Apologies for the delays in fixing this

- Listeria database: human error copying files over (should be ok hereafter as we've since automated this). Fixed on the ftp
- Neisseria database: less clear to me what happened here as the local copy is correct, but I can confirm the download is wrong. I have replaced with the corrected version

**Closed by johnlees** 2024-02-26 17:00 UTC

**Comment by DOH-JDJ0303** [comment] 2024-02-28 01:13
Hi @johnlees, thank you for fixing these but it appears there might still be one issue! The S. pyogenes link appears to download the S. pneumoniae database.

**Comment by johnlees** [comment] 2024-02-28 10:10
Thanks again for point this out!! Also fixed
